# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimetask',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
