# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_periodictask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodictask',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.RemoveField(
            model_name='periodictask',
            name='start',
        ),
        migrations.AddField(
            model_name='periodictask',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodictask',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='periodictask',
            name='every',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='periodictask',
            name='metric',
            field=models.CharField(choices=[('s', 'seconds'), ('m', 'minutes'), ('h', 'hours'), ('d', 'days'), ('w', 'weeks'), ('M', 'months'), ('y', 'years')], default='h', max_length=255),
        ),
    ]
