# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20161113_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimetask',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='rules.Profile'),
        ),
        migrations.AlterField(
            model_name='onetimetask',
            name='rules',
            field=models.ManyToManyField(blank=True, to='rules.Rule'),
        ),
        migrations.AlterField(
            model_name='periodictask',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='rules.Profile'),
        ),
        migrations.AlterField(
            model_name='periodictask',
            name='rules',
            field=models.ManyToManyField(blank=True, to='rules.Rule'),
        ),
    ]
