# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20161113_1220'),
        ('rules', '0002_profile'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('passed_rules', models.ManyToManyField(blank=True, to='rules.Rule')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.OneTimeTask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='onetimereport',
            options={},
        ),
    ]
