# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20161120_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimereport',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='schedule.OneTimeTask'),
        ),
    ]
