# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('rules', models.ManyToManyField(to='rules.Rule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
